### ISSUE TITLE
Registration page 

### ISSUE THREAD

**Issue by richarddushime** [richarddushime/Implementing-Facial-Recognition-and-Biometric-Attendance-Monitoring-in-Educational-and-Corporate-Set#22]
A registration page is needed for users to be able to register themselves , but they  will a validation method , This is just for  a view

**Comment by Raghu1124** [comment]
hey! I would like to work on the project and want to make a login-signup page for this repo, please assign me this issue

**Comment by richarddushime** [comment]
This issue is ready associated with a PR , check another issue #18
