### ISSUE TITLE
Staff Application  Tests

### ISSUE THREAD

**Issue by jovialumwari** [richarddushime/Implementing-Facial-Recognition-and-Biometric-Attendance-Monitoring-in-Educational-and-Corporate-Set#55]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Expected Behavior
There is a need of tests in the application , this falls under Testing and Quality Assurance issue Created earlier

**Comment by richarddushime** [comment]
Ready to be closed 🔒
