### ISSUE TITLE
UI refinement of User Registration form 

### ISSUE THREAD

**Issue by jovialumwari** [richarddushime/Implementing-Facial-Recognition-and-Biometric-Attendance-Monitoring-in-Educational-and-Corporate-Set#58]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

# Expected Behavior

UI Full view of the form 

# Current Behavior

some parts of the form are not seen

**Comment by jovialumwari** [comment]
Hi @richarddushime  i realised that there was an issue with UI on the Register From , some parts of it are not well aligned and seen , even the Title , i would like to work on it 
thanks

**Comment by richarddushime** [comment]
Alright Go ahead

**Comment by richarddushime** [comment]
Ready to be closed
